### ISSUE TITLE
Display issue when Path too long

### ISSUE THREAD

**Issue by simpledudeonline** [sunadarake/Personal_Blocklist#10]
Hi,
When one recorded bookmark is more than 35 characters, the display is shifted to the left, so the "Remove" buttons are not visible. So no bookmark can be removed anymore.
(otherwise works great, thanks).
![Capture](https://user-images.githubusercontent.com/67105461/85020107-c00c4980-b167-11ea-832c-235d2f3c73fe.PNG)

**Comment by FlashlightET** [comment]
still having this issue 3 years later
