### ISSUE TITLE
What does `PWS_REGEX` means in the content_script.js?

### ISSUE THREAD

**Issue by EgoPingvina** [sunadarake/Personal_Blocklist#5]
I'm interested in understanding how this extension works from the inside. If it is not so hard, can you answer this question?)
What does `PWS_REGEX` means in the content_script.js? What does PWS abbreviature means and what does this regex check?

**Comment by sunadarake** [comment]
Sorry for the late reply.

PWS means 'personalized'.

Google search determines websites to display based on your past search history.
for example, if you visit a specific website many times, Google search makes it easier for its website to show up in search results.

So, when you add &pws=0 at the end of the URL and turn off personalized search, Google displays pure search results, regardless of your search history.

I apolognize for the poor expression.
Finally, here's URLs to help you.

<a href="https://googleblog.blogspot.com/2009/12/personalized-search-for-everyone.html" target='_blank'>Official Google Blog: Personalized Search for everyone</a>

<a href="https://en.wikipedia.org/wiki/Google_Personalized_Search" target='_blank'>Google Personalized Search - Wikipedia</a>

**Comment by EgoPingvina** [comment]
> Sorry for the late reply.

No problems)

Oh, after it I have understood, thanks. But now I am not understanding why you skip search with this parameter(content_script.js:120):
`if (blocklist.searchpage.isPwsParamUsed()) return;`

If a user appended some domain to block list, he expects that it blocks every time. I think that this `if` may lead to review like:
![image](https://user-images.githubusercontent.com/9804340/82472005-2e5ddd80-9ad0-11ea-97bb-2e169f8f3415.png)

If you decide that this is so, I could create a pull request with its removal.

**Comment by EgoPingvina** [comment]
Or it can be like a checkbox for user. I think it will be even better)

**Comment by sunadarake** [comment]
I've thought about PWS a lot, but I think we should remove it without adding the checkbox.

Originally, I included the PWS feature because it was intended to be used for SEO research.
However,  some people seem to be using PWS just to see Google's English search result.

And, when we want to see pure search result, it is very easy to use "Secret browsing" without PWS. (Only click `ctrl` + `shift` + `N`)

Ofcource, I thought about adding the checkbox too,  but I want to keep this extension simple.

If there's no problem, I'll write the update patch.

**Comment by EgoPingvina** [comment]
Little possibility of customization shouldn't become a complication for users, but it can show care about them.

**Comment by EgoPingvina** [comment]
I sent my version of the solution like PR https://github.com/sunadarake/Personal_Blocklist/pull/7

Look at it, maybe this is what you need

**Comment by sunadarake** [comment]
Thanks for your PR, but there are a few bug in your code.

I've taken your option and decided to add checkbox for PWS.

As I mentioned before, I want to make this extension simple.
So I add checkbox without option area. (as shown in the image below.)

<img width="393" alt="Screen Shot 2020-05-23 at 12 31 08" src="https://user-images.githubusercontent.com/33715405/82720866-7c522b80-9cf2-11ea-8b75-c5d3b5823033.png">

**Comment by EgoPingvina** [comment]
You want to make it simple, but pile up the window with new functionality instead of breaking it into small simple pieces.

About which bugs are you talking? I think they can be easily fixed.

**Comment by sunadarake** [comment]
Sorry. I may have been wrong about the bug. 
I guess that means your PR provided the sample functionality.

Now there is only PWS option in this extensions, so I'll deal with the problem as shown in the image above.
But when this extension has more options, we'll do it the way you suggest.
(I wouldn't want more options if I could.)
